### ISSUE TITLE
actionBarDrawerToggle expecting ActionBarDrawerToggle instead of Boolean

### ISSUE THREAD

**Issue by Quintasan** [zsmb13/MaterialDrawerKt#46]
Not sure if this is an actual bug but the original library has the following code:

```java
new DrawerBuilder()
	.withActivity(this)
	.withTranslucentStatusBar(false)
        .withActionBarDrawerToggle(false)
	.addDrawerItems(
		//pass your items here
	)
	.build();
```
The following code complains about type mismatch:
```kotlin
result = drawer {
            translucentStatusBar = false
            actionBarDrawerToggle = false
            primaryItem("Home") {}
            primaryItem("Users") {}
            secondaryItem("Settings") {}
        }
```

What am I doing wrong?

**Comment by zsmb13** [comment]
Hey, that setting is available through the `actionBarDrawerToggleEnabled` property. 

It had to have a different name because the original library uses overloaded functions here, but there can't be multiple properties with different types in Kotlin. I'll add this to the documentation somewhere.
