### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by AllanWang** [zsmb13/MaterialDrawerKt#47]
It may also be worthwhile to have the user include the original dependency anyways since they can update it directly while still using your bindings rather than wait for you to update the lib with the newer material drawer version.

**Comment by zsmb13** [comment]
Is there anything to be done by me to support this? I believe that you can just include a dependency to the original library in addition to mine if you need newer features from it that aren't present in mine yet.

**Comment by AllanWang** [comment]
As of now there is a new version so if you'd like you can add that here. This was mainly just a suggestion to maybe expand on `You don't have to include the original library separately.` in case other users aren't aware of that.

**Comment by zsmb13** [comment]
Yeah, I'll get to updating to the latest version soon. And I'll change that line in the documentation then. Thanks for the suggestion.

**Comment by zsmb13** [comment]
(I'll leave this open so that I don't forget to do that)
