### ISSUE TITLE
How can I align a profile to the center without a Custom View?

### ISSUE THREAD

**Issue by jorgevalbuena56** [zsmb13/MaterialDrawerKt#51]

**Comment by zsmb13** [comment]
Can you be a bit more specific? Where are you trying to center and which part of the profile?

**Comment by jorgevalbuena56** [comment]
The profile header, where the user name, email and avatar are, I would to have them all align to the center of the drawer

**Comment by zsmb13** [comment]
This can be done, but you'll have to use your own custom XML layout for it (this can be set via the `customViewRes` property inside the `accountHeader` block), as the base library doesn't provide specific support for it. Should be fairly straightforward though, it looks like it just needs small tweaks to the original layout that the library uses.

**Comment by jorgevalbuena56** [comment]
Do you know, by any chance,  where is the XML Layout used by the original library?

**Comment by zsmb13** [comment]
Yes, I've actually looked it up, it's [this one](https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/res/layout/material_drawer_header.xml). 

It looks like you'd just have to realign the ImageView (`@+id/material_drawer_account_header_current`) and the two TextViews inside the second LinearLayout (`@+id/material_drawer_account_header_text_section`). Maybe that LinearLayout itself too.

**Comment by jorgevalbuena56** [comment]
Excellent, I'll do that and let you know

**Comment by jorgevalbuena56** [comment]
I am trying to set my new view like this:

customViewRes = R.layout.material_drawer_header

And I am getting this compile error:

![image](https://user-images.githubusercontent.com/7516423/28685920-0b0ae624-72cf-11e7-839c-51274adc3dc3.png)

**Comment by zsmb13** [comment]
I thought you wanted to center the one selected profile that's on the very top of the header. If that's what you're trying to do, then you should use the `customViewRes` property a level higher:

```kotlin
accountHeader {
    customViewRes = R.layout.something

    profile("Jane" {}
    profile("Sally") {}
}
```

Or did I misunderstand, and are you actually trying to center every profile item in the profile list?

**Comment by jorgevalbuena56** [comment]
ohh, ok, I was wrong, Yes, you r right, I moved the line there and now it's picking up the new xml

**Comment by zsmb13** [comment]
Great, it's just a matter of XML customization from there, so I'll close this. Good luck with it.
