### ISSUE TITLE
How to get rid of the switch icon

### ISSUE THREAD

**Issue by jorgevalbuena56** [zsmb13/MaterialDrawerKt#52]
I am trying to align the profile account header (picture, email, name) to the center and I am not able to get rid of the switch icon that is on the right. Since I am using a custom view, Every time I try to delete a view, it throws an exception since It can't find it.

Is there a way to have more control of how the profile account header is drawn?

**Comment by zsmb13** [comment]
An easy solution would be to leave it there and set its visibility to either GONE or INVISIBLE.

**Comment by zsmb13** [comment]
Did you manage to solve your issue?

**Comment by jorgevalbuena56** [comment]
I was, but I don't like the fix. The library is not flexible enough to do small changes like the ones I am doing. I don't understand why do I have to keep the original elements in the XML layout if is a custom view. The library should validate if the view is already there and avoid to do some actions. I should be able to have my very own views and still working fine. Now I am stuck with a bunch of unused views with visibility GONE (switcher, images from other profiles at the right side, etc)

Also I had to add a hack to align the name and email since the library dynamically adds some padding to the end:

       result.header.findViewById<ImageView>(R.id.material_drawer_account_header_text_switcher).visibility = View.GONE
        result.header.findViewById<LinearLayout>(R.id.material_drawer_account_header_text_section).setPadding(0,0,0,0)

**Comment by zsmb13** [comment]
You'll have take the issue about flexibility to the [original library](https://github.com/mikepenz/MaterialDrawer). This one is just the Kotlin wrapper, so they are functionally equivalent.
