### ISSUE TITLE
Add/Remove after initialize

### ISSUE THREAD

**Issue by dev12-SC** [zsmb13/MaterialDrawerKt#57]
How add/Remove items after initialize using KtLib??
Has issues talk ifself but no found Drawer.Result as explained in issue  i read.

I try using this form 
mDrawer.addItem( mPrimaryItem )

Sorry my english and Thanks for Lib.

**Comment by zsmb13** [comment]
This library only provides a DSL for describing the initial drawer. If you want to dynamically modify the contents later, you'll have to use the API of the base library, for example:

```kotlin
val result = drawer {
    primaryItem("foo")
    secondaryItem("bar")
}

result.addItem(PrimaryDrawerItem().withName("qwert"))
result.removeItemByPosition(0)
```

**Comment by zsmb13** [comment]
Does the above solve your problem?

**Comment by dev12-SC** [comment]
@zsmb13 Yes, Tanks!
