### ISSUE TITLE
Facing oncreateview overrides nothing in fragments

### ISSUE THREAD

**Issue by inders** [zsmb13/MaterialDrawerKt#63]
just including the dependency is hitting this. Any pointers would help.

**Comment by zsmb13** [comment]
Hey, check [this StackOverflow question](https://stackoverflow.com/q/47250787/4465208), you might be facing the same issue with support library 27.

**Comment by zsmb13** [comment]
Any luck with your issue since?

**Comment by zsmb13** [comment]
Marking this as closed for now.
