### ISSUE TITLE
OnDrawerItemClick

### ISSUE THREAD

**Issue by MahmoodAliHasan** [zsmb13/MaterialDrawerKt#64]
How to setOnDrawerItemClick only when item is not selected

**Comment by zsmb13** [comment]
You can use the version of the `onClick` method that takes a 3 parameter lambda, and then check if the drawer item is selected inside the listener:

```kotlin
primaryItem("My item") {
    onClick { view, position, drawerItem ->
        if(drawerItem.isSelected) {
            // perform actions here
            true
        } else {
            false
        }
    }
}
```

**Comment by zsmb13** [comment]
Closing this for now due to inactivity.
