### ISSUE TITLE
Replace "kotlin-stdlib-jre7" dependency with "kotlin-stdlib-jdk7"

### ISSUE THREAD

**Issue by valsinats42** [zsmb13/MaterialDrawerKt#69]
Hi! When using MaterialDrawerKt with Android Studio 3.1.2, I'm getting a build warning: "kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead". Hopefully it should be a trivial fix, thanks!

**Comment by zsmb13** [comment]
Good catch, cheers :)

**Comment by zsmb13** [comment]
This finally made it into a release, thanks again!
