### ISSUE TITLE
Targeting API 28 results in crash - Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed

### ISSUE THREAD

**Issue by queiroz** [zsmb13/MaterialDrawerKt#70]
```
    java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
        at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
        at android.graphics.Canvas.saveLayer(Canvas.java:455)
        at com.mikepenz.materialdrawer.view.BezelImageView.onDraw(BezelImageView.java:213)
```
this is related to issue [#2293](https://github.com/mikepenz/MaterialDrawer/pull/2293) of MaterialDrawer.

**Comment by zsmb13** [comment]
If I understand correctly, this has been fixed in version 6.0.8 of the base library. This library will be updated to use that version (and therefore fix this) as soon as [this other issue](https://github.com/mikepenz/MaterialDrawer/issues/2312) is fixed over there.

**Comment by queiroz** [comment]
@zsmb13 awesome, thanks for replying!

**Comment by queiroz** [comment]
@zsmb13 the issue has now been fixed, can you upgrade to 6.0.8?

**Comment by zsmb13** [comment]
Finally done, you can go ahead and grab 1.3.5 on jcenter.

**Comment by derlysbenito** [comment]
where the base library is updated in Android Studio ? help please

**Comment by sawant98d** [comment]
upgrading to 6.0.8 is really helped me.. Thanks zsmb13
