### ISSUE TITLE
Builder object doesn't seem to be accessible?

### ISSUE THREAD

**Issue by sandyscoffable** [zsmb13/MaterialDrawerKt#71]
The FAQ states the following:
> I want to use features of the base library that haven't made it to this one yet
>
> If the base library gets features and they aren't ported to this wrapper yet, you can include that as a dependency in addition to this one, and use the two together. For these purposes, the internal DrawerBuilder that this library uses is exposed through a property, and you can access it like so:
> 
> drawer {
>     builder.withKeepStickyItemsVisible(true)
> }

However, I get the following error when trying to do this in Android Studio:

![screen shot 2018-06-12 at 11 20 00](https://user-images.githubusercontent.com/20515901/41284899-98285cc6-6e32-11e8-93da-bfd46a1ab55c.png)

What am I doing wrong? 😄

**Comment by zsmb13** [comment]
Whoops, sorry, these `builder` properties were [made internal](https://github.com/zsmb13/MaterialDrawerKt/commit/da1fcd867961c206831102a1094f9166365206d5) without considering these use cases - or updating the README, for that matter. 

They'll be public again in the next release, which we'll be out as soon as the base library fixes [this issue](https://github.com/mikepenz/MaterialDrawer/issues/2312), which is currently breaking builds.

**Comment by sandyscoffable** [comment]
Thanks ❤️

**Comment by zsmb13** [comment]
This fix is present in the now published 1.3.5 release that's live on jcenter.
