### ISSUE TITLE
expandable item bug: sub items added twice

### ISSUE THREAD

**Issue by or-dvir** [zsmb13/MaterialDrawerKt#73]
hi.
I get duplicate sub-items for an expandable item. am I doing something wrong?
here is my code:

```
expandableItem {
                nameRes = R.string.moreInfo
                icon = R.drawable.ic_more_info

                attachItem(secondaryItem {
                    nameRes = R.string.officialSite
                })
```

and here is the outcome 
![capture _2018-08-02-17-26-56_01](https://user-images.githubusercontent.com/17179542/43590326-413b04b2-9660-11e8-91bc-c928c15a6f34.png)

**Comment by zsmb13** [comment]
You don't need to attach the items inside the expandable drawer item yourself:

```kotlin
expandableItem("Expandable drawer item", "Expandable drawer item description") {
    iicon = FontAwesome.Icon.faw_heart
    primaryItem("Expanded item 1") {
        iicon = FontAwesome.Icon.faw_magic
        level = 2
    }
    primaryItem("Expanded item 2") {
        iicon = FontAwesome.Icon.faw_magic
        level = 2
    }
}
```

The example is from the example app, specifically [here](https://github.com/zsmb13/MaterialDrawerKt/blob/master/app/src/main/java/co/zsmb/materialdrawerktexample/newactivities/DrawerItemTypesActivity.kt#L71).

**Comment by or-dvir** [comment]
thanks everything is fine now.
suggestion: not sure if it's possible due to this being a wrapper library, but maybe you can make functions that are **not** meant to be called by the user `private`?

**Comment by zsmb13** [comment]
This function has to be accessible so that custom drawer items can be added to the DSL. However, it's _supposed to_ have a Deprecation warning so you don't use it accidentally. The warning was there in the library, just not everywhere - I'll fix this in the next release, thanks for finding it! :)
